# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  lint:
    docker:
      - image: python:3.6.5-alpine

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Installing Make
          command: apk add --update make

      - run:
          name: Installing Pipenv
          command: pip install pipenv

      - run:
          name: Installing Dependencies
          command: make install
        
      - run:
          name: Linting
          command: make lint

      - persist_to_workspace:
          root: .
          paths:
            - .

  package_and_upload:
    docker:
      - image: python:3.6.5-alpine

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Installing Make
          command: apk add --update make

      - run:
          name: Installing AWS CLI
          command: pip install awscli 

      - run:
          name: Installing Pipenv
          command: pip install pipenv

      - run:
          name: Installing Dependencies
          command: make install

      - run:
          name: Packaging and uploading
          command: |
            cd deploy/
            pipenv run ./deploy.py --stages upload --env prod --save-artifact-s3-keys artifact-s3-keys.json

      - run:
          name: Creating GitHub release
          command: ./deploy/create_gh_release.py --release --archive-locations-file artifact-s3-keys.json

workflows:
  version: 2
  lint_package_and_upload:
    jobs:
      - lint
      - package_and_upload:
          requires:
            - lint
          filters:
            branches:
              only: master
